modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "mptest"
version = "${version}"
displayName = "Multiplatform Test Mod"
authors = "yezhiyi9670"
description = '''
Architectury + Forgix test mod.
'''
#logoFile = ""

[[dependencies.mptest]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mptest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"
